x-template: &default-template
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: '1g'
      max-file: '5'


services:
  api:
    <<: *default-template
    build:
      context: ./api
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - app-network

  app:
    build:
      context: ./app
    volumes:
      - app_static_files:/usr/src/app/build

  nginx:
    <<: *default-template
    image: nginx:latest
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - app_static_files:/usr/share/nginx/html:ro
    depends_on:
      - app
      - api
    networks:
      - app-network
      - ssl-proxy

  ssl-proxy:
    <<: *default-template
    build:
      context: ./ssl-proxy
    environment:
      - PUID=1000
      - PGID=1000
      - URL=spygame.garbacz.dev
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - ./ssl-proxy/etc:/config/etc
      - ./ssl-proxy/keys:/config/keys
      - ./ssl-proxy/log:/config/log
    ports:
      - 80:80
      - 443:443
    depends_on:
      - nginx
    networks:
      - ssl-proxy


networks:
  app-network:
  ssl-proxy:

volumes:
  app_static_files:
